version: '3'
services:
  nginx:
    build: ./nginx
    image: your_repo/nginx-stable-alpine
  node-app:
    build: ./node
    image: your_repo/js-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    container_name: mongo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    container_name: redis

volumes:
  mongo-db:
