version: "3"
services:
  jenkins:
    build: ./jenkins_build
    volumes:
      - ./jenkins_home:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ~/.aws/:/var/lib/jenkins/.aws
    image: yarinhill/jenkins
    user: jenkins
    privileged: true
    restart: always
    container_name: jenkins
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOME: "/var/lib/jenkins"
      JENKINS_HOME: "/var/lib/jenkins"
      JENKINS_OPTS: "--httpPort=8080"
